### ISSUE TITLE
`interactive_webview` does not specify a Swift version

### ISSUE THREAD

**Issue by abozanona** [duyduong/interactive_webview#14]
When I try to run on IOS I get this error

```
    [!] Unable to determine Swift version for the following pods:

    - `interactive_webview` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the
    author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:578:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
```

**Comment by abozanona** [comment]
I fixed this issue by forking the repo and making those changes([9d91e57](https://github.com/abozanona/interactive_webview/commit/9d91e57d1d10ba19015515ed7d9cd17b242f0f37) , [b4860e6](https://github.com/abozanona/interactive_webview/commit/b4860e63cb5be231a8a2ff7ab882380645e58503) & [4c00dd9](https://github.com/abozanona/interactive_webview/commit/4c00dd9c78c60238a775fbbf2c03d697fee8c126)).
And by following [this](https://github.com/kiwi-bop/flutter_crashlytics/issues/37#issuecomment-441860231) advice.

And to import the plugin from github, add this to `pubspec.yaml`

```
dependencies:
# interactive_webview: ^0.1.2
  interactive_webview:
    git:
      url: git://github.com/abozanona/interactive_webview.git
      ref: master

```
@duyduong I'm not an IOS/Swift expert, and I'm not sure if this the best way to solve this issue. 
Please consider fixing the issue on this repo.
